blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/blairg23/toolshed/security/advisories/new
    about: Please privately disclose security issues through GitHub Security Advisories.
